import random

random_number1 = random.randint(1, 9)
random_number2= random.randint(1, 9)
random_number3 = random.randint(1, 9)
letters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
random_letter1 = random.choice(letters)
random_letter2 = random.choice(letters)
random_letter3 = random.choice(letters)
random_letter4 = random.choice(letters)
random_letter5 = random.choice(letters)
random_letter6 = random.choice(letters)
random_letter7 = random.choice(letters)
random_letter8 = random.choice(letters)
random_letter9 = random.choice(letters)
random_number11 = random.randint(1, 9)
random_number22 = random.randint(1, 9)
random_number33 = random.randint(1, 9)
random_letter11 = random.choice(letters)
random_letter22 = random.choice(letters)
random_letter33 = random.choice(letters)
random_letter44 = random.choice(letters)
random_letter55 = random.choice(letters)
random_letter66 = random.choice(letters)
random_letter77 = random.choice(letters)
random_letter88 = random.choice(letters)
random_letter99 = random.choice(letters)

print(f"{random_number1}{random_number2}{random_letter1}{random_number3}-{random_letter2}{random_letter3}{random_letter4}{random_letter5}-{random_letter6}{random_letter7}{random_letter8}{random_letter9}")
print(f"{random_number11}{random_number22}{random_letter11}{random_number33}-{random_letter22}{random_letter33}{random_letter44}{random_letter55}-{random_letter66}{random_letter77}{random_letter88}{random_letter99}")
